save_dir: ckpt/demo

data_dir: data/demo
train_file: train.json
dev_file: dev.json
test_file: test.json
max_sent_len: 200
max_subword_len: 512
entity_schema: BIEOU
low_case: 1
pretrained_embeddings_file: data/embedding/glove.6B.100d.txt.gz

embedding_dims: 100
word_dims: 100
char_dims: 50
char_batch_size: 128
char_kernel_sizes: [2, 3, 4]
char_output_channels: 25
embedding_dropout: 0.1
embedding_model: pretrained
entity_model: pipeline
lstm_layers: 0
lstm_hidden_unit_dims: 512
lstm_dropout: 0.1
entity_cnn_kernel_sizes: [2, 3, 4]
entity_cnn_output_channels: 100
ent_output_size: 300
span_batch_size: 256
ent_batch_size: 256
schedule_k: 3.0
context_cnn_kernel_sizes: [3, 4, 5]
context_cnn_output_channels: 100
context_output_size: 300
ent_mention_output_size: 512
dropout: 0.1
pretrained_model_name: bert-base-uncased
ptm_output_size: 0
ptm_dropout: 0.1

adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-6
adam_weight_decay_rate: 0.01

seed: 5216
epochs: 200
pretrain_epochs: 0
warmup_rate: 0.2
early_stop: 100
train_batch_size: 32
gradient_clipping: 1.0
gradient_accumulation_steps: 1
learning_rate: 3e-5
ptm_learning_rate: 25e-6
test_batch_size: 32
validate_every: 15000
device: -1

logging_steps: 32
root_log_level: DEBUG
log_file: train.log
console_log_level: NOTSET
file_log_level: NOTSET
